-- IMPORT RECIPE IMAGES
-- DELETE FROM public.recipe_images; -- Opcional: Limpiar antes
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Atún con huevo duro', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/atun-con-huevo-duro.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Berenjena al horno con carne magra', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/berenjena-al-horno-con-carne-magra.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Caldo de pollo casero', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/caldo-de-pollo-casero.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Carne magra con ensalada', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/carne-magra-con-ensalada.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Ensalada de atún y tomate', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/ensalada-de-atun-y-tomate.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Ensalada de garbanzos light', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/ensalada-de-garbanzos-light.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Ensalada de lentejas light', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/ensalada-de-lentejas-light.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Ensalada de pollo a la plancha', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/ensalada-de-pollo-a-la-plancha.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Ensalada de quinoa y pollo', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/ensalada-de-quinoa-y-pollo.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Merluza con espinaca', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/merluza-con-espinaca.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Omelette de claras con verduras', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/omelette-de-claras-con-verduras.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Pechuga de pollo con ensalada verde', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/pechuga-de-pollo-con-ensalada-verde.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Pescado al horno con verduras', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/pescado-al-horno-con-verduras.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Pollo al limón con ensalada', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/pollo-al-limon-con-ensalada.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Pollo con brócoli al vapor', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/pollo-con-brocoli-al-vapor.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Revuelto de claras con champiñones', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/revuelto-de-claras-con-champinones.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Sopa de verduras', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/sopa-de-verduras.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Tortilla de espinaca light', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/tortilla-de-espinaca-light.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Wrap de lechuga con pollo', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/wrap-de-lechuga-con-pollo.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;
INSERT INTO public.recipe_images (recipe_name, image_url) VALUES ('Zucchini relleno de pollo', 'https://lbxjyxovbcprhatsbvkp.supabase.co/storage/v1/object/public/photos/recipes/zucchini-relleno-de-pollo.jpg') ON CONFLICT (recipe_name) DO UPDATE SET image_url = EXCLUDED.image_url;