export interface ExerciseEntry {
  name: string;
  muscle_group: string;
  category: string;
  description: string;
  muscles: string;
  joint_type: string;
}

export const MUSCLE_GROUPS = [
  "Pecho", "Espalda", "Hombros", "Bíceps", "Tríceps",
  "Cuádriceps", "Isquiotibiales", "Glúteos", "Pantorrillas",
  "Abdominales", "Antebrazos", "Trapecio", "Cuerpo completo", "Core",
];

export const EXERCISE_CATEGORIES = [
  { value: "compound", label: "Compuesto" },
  { value: "isolation", label: "Aislamiento" },
  { value: "calisthenics", label: "Calistenia" },
  { value: "crossfit", label: "CrossFit" },
  { value: "mobility", label: "Movilidad" },
  { value: "stretching", label: "Estiramiento" },
];

export const EXERCISE_CATALOG: ExerciseEntry[] = [
  // ═══════════════════ PECHO ═══════════════════
  { name: "Press banca con barra", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor (esternocostal). Secundarios: Deltoides Anterior, Tríceps Braquial.", description: "Mecánica: Retracción escapular activa y depresión de hombros para proteger articulación glenohumeral. Descenso con control excéntrico hasta rozar el esternón bajo, seguido de empuje de fuerza pura (leg drive activo)." },
  { name: "Press banca inclinado con barra", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor (fibras claviculares), Deltoides Anterior, Tríceps.", description: "Mecánica: Ángulo 30-45° enfocado en hipertrofia superior torácica. Descender lentamente hacia las clavículas evitando el rebote, aplicando rotación interna máxima al subir." },
  { name: "Press banca declinado con barra", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor (inferior), Tríceps.", description: "Mecánica: Inclinación negativa 15-30°. Aísla la porción inferior reduciendo stress del deltoides anterior. Ideal para sobrecargas máximas en contracción pico torácica." },
  { name: "Press inclinado con mancuernas", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor (clavicular), Serrato Anterior, Deltoides.", description: "Mecánica: Abducción de hombros a 45 grados logrando ROM libre y mayor estiramiento fascial inferior superando las barreras de asimetría típicas de la barra rígida." },
  { name: "Press plano con mancuernas", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor hipertrofia total.", description: "Mecánica: Torsos fijados y arco natural. Las mancuernas dictan el arco de aducción horizontal generando contracción central profunda y corrección de disbalances musculares." },
  { name: "Press declinado con mancuernas", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Mayor inferior.", description: "Mecánica: Arco estrecho inferior de aducción cruzada. Logra contracción de las crestas pectorales y cortes fibrosos bajo máxima abducción de codo reduciendo pinzamiento de hombros." },
  { name: "Aperturas con mancuernas plano", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral Mayor aislado.", description: "Mecánica: Ejercicio matriz de estiramiento miofibrilar horizontal. Mantén rigidez en codos levemente flexionados absorbiendo el impacto coracoides solo con vector torácico puro." },
  { name: "Aperturas inclinadas con mancuernas", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral Mayor superior/clavicular.", description: "Mecánica: Aislamiento severo de inserciones altas al frente de la caja escapular rotando fibras con codos elevados para destruir umbrales estáticos pectorales." },
  { name: "Crossover en polea alta", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral Inferior y Medio (tensión continua).", description: "Mecánica: Tracción convergente descendente sobre cable. Genera isquemia en pico de tensión al cruzar muñecas, activando estriaciones medias brutales pre-esternales." },
  { name: "Crossover en polea baja", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral Superior y Coracobraquial.", description: "Mecánica: Acción 'uppercut' ascendente bloqueando lumbares, obligando a las fibras elásticas subclaviculares a manejar la fuerza estática al final de la curva de fuerza." },
  { name: "Press en máquina Smith", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Red global torácica prensa guiada.", description: "Mecánica: Línea vectorial congelada. Ideal para agotar o reclutar fallos sistémicos sin la necesidad de fatigar músculos secundarios encargados del balance estructural." },
  { name: "Press en máquina convergente", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral central.", description: "Mecánica: Diseño biomecánico estricto cerrando arco de aducción concéntrica al frente, alineando al 100% con direcciones anatómicas del abanico esternal." },
  { name: "Pec deck (mariposa)", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral central e interior agudo.", description: "Mecánica: Máquina rotatoria de pivote en codos o muñecas, exprime la barrera de presión al final de rango eliminando toda inercia, puro fuego hipertrófico vascular." },
  { name: "Pullover con mancuerna", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectoral Mayor transversal, Dorsal, Serratos Intercostales.", description: "Mecánica: Expansión de caja torácica cruzada por encima del rostro estirando músculos intercostales y ensanchando diafragma con ROM longitudinal peligroso pero anabólico." },
  { name: "Fondos en paralelas (pecho)", muscle_group: "Pecho", category: "compound", joint_type: "Multiarticular", muscles: "Pectoral Inferior, Tríceps Braquial, Hombro Deltoideo posterior.", description: "Mecánica: Inclinación frontal 30-40°, pelvis neutral, barbilla encajada. Produce adaptaciones fibrilares agresivas de tejido denso constructor estético del borde esternal bajo." },
  { name: "Flexiones de pecho", muscle_group: "Pecho", category: "calisthenics", joint_type: "Multiarticular", muscles: "Cadenas frontales cerradas (Pecho, Core tensado, Tríceps).", description: "Mecánica: Calistenia maestra. Control lumbo-pélvico PPT para asegurar reclutamiento primario delto-pectoral rozando vientre con piso en el estiramiento final máximo." },
  { name: "Flexiones diamante", muscle_group: "Pecho", category: "calisthenics", joint_type: "Multiarticular", muscles: "Tríceps Vasto Medial masivo, Fibras pre-esternales densas.", description: "Mecánica: Manos unidas en eje central forzando hipertrofia interna al reducir la base al mínimo e incrementar torsión central sobre epicóndilos, exigencia absoluta del tríceps." },
  { name: "Flexiones declinadas", muscle_group: "Pecho", category: "calisthenics", joint_type: "Multiarticular", muscles: "Pectoral Superior y Hombros en pico gravitatorio.", description: "Mecánica: Elevación basal de tobillos que transfiere peso y palanca directo sobre base subclavicular reclutando fibras comúnmente en déficit fuerza-volumen." },
  { name: "Flexiones con palmada", muscle_group: "Pecho", category: "calisthenics", joint_type: "Multiarticular", muscles: "Pectoral explosivo Pliométrico (Fibras contracción ultra-rápida IIb).", description: "Mecánica: Expresión pliométrica rompiendo la inercia con energía cinética reactiva superándolo en umbrales de potencias neuronales y conectividad miofibrilar elástica pura." },
  { name: "Svend press", muscle_group: "Pecho", category: "isolation", joint_type: "Monoarticular", muscles: "Pectorales estrías internas y pre-esternales estáticas.", description: "Mecánica: Isometría Isotónica de apretar frontal un disco o plato frente al pecho y estirar brazos al bloqueo. Esculpe y parte la separación de las placas torácicas centrales visuales." },
  
  // ═══════════════════ ESPALDA ═══════════════════
  { name: "Dominadas agarre prono", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Dorsal Ancho puro, Redondo Mayor amplio.", description: "Mecánica: Cadena cinética cerrada Rey. Retracción-depresión escapular de arranque (dead hang). Levantar cruzando la barra por debajo del tórax expandiendo el frente superior global dorsal." },
  { name: "Dominadas agarre supino (chin-up)", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Lats bajos y Bíceps braquial en isometría total flexora.", description: "Mecánica: Favorece la palanca anatómica acortando bíceps con extrema carga concéntrica final permitiendo sobrecarga al ancho bajo de romboides medios profundos y fuertes lats inferiores." },
  { name: "Dominadas agarre neutro", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Braquiorradial, Espalda profunda centro.", description: "Mecánica: Elimina estrés en las cápsulas gleno-humerales. Genera una potente tensión central y tracción masiva sin límite doloroso conectando todo el marco lateral romboide y braquial potente anterior." },
  { name: "Dominadas agarre amplio", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Redondo Mayor y Anchura Visual Dorsal en arco lateral.", description: "Mecánica: Aisla el trabajo sobre el borde externo cortando al mínimo contribución bicipital exigiendo máxima expansión a nivel de omoplatos estiramiento lateral ala." },
  { name: "Remo con barra agarre prono", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Espalda Global Media. Trapecios Medio/Inferior.", description: "Mecánica: Inclinación pélvica de 45°, core bloqueado hierro. Tirón firme llevando barra al abdomen bajo usando codos retroactivos como guías de gancho apretando tejido supra escapular superior grueso." },
  { name: "Remo con barra agarre supino", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Dorsal inferior de ensamble bajo crestas (Estilo Yates).", description: "Mecánica: Postura inclinada semi-erguida rozando barra muslo para hipertrofiar bases lumbares y densidades internas profundas que anclan bíceps con cadena media completa pesada dura letal profunda y dura masiva densa total." },
  { name: "Remo con mancuerna a una mano", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Dorsal largo asilado isométrico oblicuo.", description: "Mecánica: Torque profundo. Posición de banco apoyado rompe simetría corporal fortaleciendo desbalances cruzados y elongación pre-tensión permitiendo arco rango gigante al lado de la cadera extrema rotatoria masiva." },
  { name: "Remo en máquina T", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Centro neural espalda densidad alta romboidal masiva pura.", description: "Mecánica: Abdomen contenido pecho estabilizado plataforma inclinada permitiendo estrujar músculos paravertebrales desde anclajes espinales hasta caja axilar externa bajo segura biomecánica controlada romboide total masiva." },
  { name: "Remo sentado en polea baja", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Trapecios Medio-Menor Dorsal longitudinal total grueso plano bajo profundo grueso denso media central fina densa dura.", description: "Mecánica: Fijación lumbar. Mantener 90 grados caderas estáticas. Aislar la escápula retraída soltando hombros bajo polea pre-tensa y estirando codos zaga hasta rozar costillas. Hipertrofia espesor segura masiva densa estable control." },
  { name: "Jalón al pecho agarre amplio", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "V-Taper Latissimus Dorsi Extremo y braquiales anchos laterales puros superior amplios masivos densos fuertes rígidos externos ala pura alta superior", description: "Mecánica: Sentado vertical codos divergentes jalando plano coronal barra hacia hueco esternal aislando anchos laterales pre-tensión sin fatigarse cadera rompiendo estancamiento dorsales y ampliando chasis." },
  { name: "Jalón al pecho agarre cerrado", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Masa Interna, Braquio Radial. Longitud lat profunda total interna fina rígida larga", description: "Mecánica: El agarre en herradura / V tira codos planos sagitales extendiendo inserciones mas profundas hacia cresta provocando pico acortamiento contráctil final apretado lumbodorsal masiva densa central superior interior pura dura fina masiva densa gruesa central fuerte." },
  { name: "Peso muerto convencional", muscle_group: "Espalda", category: "compound", joint_type: "Multiarticular", muscles: "Extensión total sistema nervioso esqueleto axial. Erectores isquio glúteos titanio fuerza pura global absoluta máxima olímpica titánica masiva fuerte denso superior baja ruda pesada real bestial olímpica dura gigante colosal absoluta de alta densidad", description: "Mecánica: Rey de los levantamientos de potencia. Hinge sagitario rodillas semifijas tensión pre cuádriceps, dorsal cerrado para blindar core empuje vertical suelo. Cadena total." },
  { name: "Face pull", muscle_group: "Espalda", category: "isolation", joint_type: "Multiarticular", muscles: "Deltoides posterior rotadores externos trapecio curativo postural masivo denso", description: "Mecánica: Tirón a polea a nivel craneal. Abre omóplatos apretando manguito rotador. Previene pinzamiento patológico de atletas corrige postura sedentarios." },

  // ═══════════════════ HOMBROS ═══════════════════
  { name: "Press militar con barra de pie", muscle_group: "Hombros", category: "compound", joint_type: "Multiarticular", muscles: "Deltoides Anterior Medio y Core estático Titánico tensor vertical masivo presión superior axial estabilizada core absoluto fuerza matriz superior constructora bestial", description: "Mecánica: Pies firmes, glúteos contraídos, barra frontal. Empuje hasta línea orejas cabeza introducida. Levanta peso base de tronco sin fallos lumbares." },
  { name: "Press Arnold", muscle_group: "Hombros", category: "compound", joint_type: "Multiarticular", muscles: "Fibras Deltoides Circulares Multiaxiales Frontal Lateral", description: "Mecánica: Curl supino interno mutado en excéntrico giratorio prono externo hiper-activador en todas cabezas abarcando volumen completo redondo." },
  { name: "Elevaciones laterales con mancuernas", muscle_group: "Hombros", category: "isolation", joint_type: "Monoarticular", muscles: "Porción Lateral Deltoide Estética pura", description: "Mecánica: Aisla amplitud clavicular ensanchando traza esquelética visible. Servir agua con el meñique guiando para golpear el segmento medio sin ayuda." },
  { name: "Pájaros con mancuernas", muscle_group: "Hombros", category: "isolation", joint_type: "Monoarticular", muscles: "Deltoides Posterior infraespinosos y trapecio bajo denso redondo sano fuerte posterior alta gama 3D volumen zaga total de corte esférico posterior absoluto rústico", description: "Mecánica: Tronco de pívot perpendicular suelo. Aislamiento abductor eliminando balanceo para esculpir parte zaga del hombrote estética redondeada 3D." },
  { name: "Push press", muscle_group: "Hombros", category: "compound", joint_type: "Multiarticular", muscles: "Generador de Potencia Fuerza Base Impulso Corporal Tren Sup/Inf combinado masivo carga", description: "Mecánica: Usa tracción dip de sentadilla cuarto transfiriendo el 30% del peso a las piernas sobrecargando hombros fase cénit por inercia bruta superior." },

  // ═══════════════════ BÍCEPS ═══════════════════
  { name: "Curl con barra recta", muscle_group: "Bíceps", category: "isolation", joint_type: "Monoarticular", muscles: "Bíceps Braquial Completo Cabeza Corta y Larga Supinación Real Total Bloque Constructor", description: "Mecánica: Agarre neutro o amplio supino extenuando el radio. Requiere postura erguida rígida; codos anclados costillas empujando fibras en su eje puro." },
  { name: "Curl concentrado", muscle_group: "Bíceps", category: "isolation", joint_type: "Monoarticular", muscles: "Pico Bicipital Cabeza Corta Cima Estética Volumen", description: "Mecánica: Fijación en vasto medio cadera flexa total. Aisla completamente sin músculos estabilizadores, traccionando masa contráctil para pico superior estético Arnold." },

  // ═══════════════════ TRÍCEPS ═══════════════════
  { name: "Press francés con barra Z", muscle_group: "Tríceps", category: "isolation", joint_type: "Monoarticular", muscles: "Cabeza Larga Tríceps Volumen Trasero Grueso Superior Largo (Skullcrusher)", description: "Mecánica: Bloqueo de codos al zenit. Excéntrica profunda atrás del cráneo provocando desgarros controlados en porción larga para crecer brazos masivos." },
  { name: "Extensión de tríceps en polea con cuerda", muscle_group: "Tríceps", category: "isolation", joint_type: "Monoarticular", muscles: "Herradura Vasta Tríceps Cabeza Lateral Cortada", description: "Mecánica: Torsión en fase final abriendo extremos estimulando fibras laterales. Bloquear el tren superior para evitar empuje con lumbares." },

  // ═══════════════════ CUÁDRICEPS ═══════════════════
  { name: "Sentadilla con barra (back squat)", muscle_group: "Cuádriceps", category: "compound", joint_type: "Multiarticular", muscles: "Sistema Inferior Cuadricipital completo, Glúteos y Core", description: "Mecánica: Respiración excéntrica diafragmática. Hinge pélvico estabilizado rompiendo cajón 90° con rodillas alineadas empujando cadena inferior vertical." },
  { name: "Sentadilla búlgara", muscle_group: "Cuádriceps", category: "compound", joint_type: "Multiarticular", muscles: "Cuádriceps Asimétrico Aislamiento Central Desequilibrio Corrector Tensor Fascia", description: "Mecánica: Carga al pie delatero asada biomecánicamente para destruir fallos laterales de piernas; brutal generador de hipertrofia isquio-cuad." },
  { name: "Prensa de piernas 45°", muscle_group: "Cuádriceps", category: "compound", joint_type: "Multiarticular", muscles: "Masa total Pierna Vector Diagonal empuje cerrado", description: "Mecánica: Desliga la fatiga axial espinal permitiendo aislar sobrecargas mecánicas extremas sobre la lágrima frontal, no retroversar cadera al bajar." },

  // ═══════════════════ ISQUIOTIBIALES Y GLÚTEOS ═══════════════════
  { name: "Peso muerto rumano con barra", muscle_group: "Isquiotibiales", category: "compound", joint_type: "Multiarticular", muscles: "Cadena Posterior Femorales y Glúteo Mayor", description: "Mecánica: Sentadilla inhibida semi recta. Todo el trabajo recae en bisagra de caderas estirando la cuerda isquiotibial hasta umbral de contracción elástica." },
  { name: "Hip thrust con barra", muscle_group: "Glúteos", category: "compound", joint_type: "Multiarticular", muscles: "Glúteo Mayor Concentrado Extremo Empuje", description: "Mecánica: Eje púbico con apoyo de banco escapular. Puente de glúteos pesados sosteniendo contracción zenit y controlando inercia baja para hiperplasia tisular." },
  
  // ═══════════════════ ANTEBRAZOS (NUEVOS MÓDULOS DE ALTA GAMA) ═══════════════════
  { name: "Curl de muñeca pronado", muscle_group: "Antebrazos", category: "isolation", joint_type: "Monoarticular", muscles: "Extensores dorsales antebrazo, Braquiorradial hipertrofia.", description: "Mecánica: Antebrazo apoyado prono en banco. Máxima rotación de carpos aislando músculos que conectan dedos a codo engrosando vascularidad externa frontal muñeca densa." },
  { name: "Curl de muñeca supino con mancuernas", muscle_group: "Antebrazos", category: "isolation", joint_type: "Monoarticular", muscles: "Grandes vientres palmares (Flexor radial, palmar mayor y profundo).", description: "Mecánica: Extender los dedos en la bajada hasta la falange pre tensionando el tendón antes de enrollar de golpe la mancuerna al antebrazo. Contracción colosal masa interna braquial inferior firme dura gigante gruesa densa masiva gruesa superior dura densa y de agarre." },
  { name: "Paseo del granjero con barra", muscle_group: "Antebrazos", category: "compound", joint_type: "Multiarticular", muscles: "Apretadores dactilares profundos isométricos, Trapecios core estabilizador absoluto titanico agarre hierro.", description: "Mecánica: Sostener carga brutal lateral (Farmers walk). Demanda extrema del Sistema Nervioso en agarre de compresión sostenida. Trabaja la fuerza funcional cruda de mano superior y densificando antebrazos bloqueando el core andante rústico grueso masivo fuerte duro firme denso central titan." },
  { name: "Curl Zottman", muscle_group: "Antebrazos", category: "isolation", joint_type: "Monoarticular", muscles: "Bíceps braquial excéntrico, braquiorradial y compartimento extensor cubital dorsal estallante fuerte duro", description: "Mecánica: Rizos concéntricos supinos de mancuerna bloqueando arriba girando pronos en descenso quemando el complejo radíal lateral estallante estriando y separando tejido bíceps de cúbito generando volúmen lateral masivo antebrazo ancho poderoso frontal tridimensional firme duro de corte grueso denso superior." },
  
  // ═══════════════════ CORE / CALISTENIA ═══════════════════
  { name: "Crunch en polea alta", muscle_group: "Abdominales", category: "isolation", joint_type: "Monoarticular", muscles: "Recto abdominal bajo tensión pesada continua estática y rotatoria.", description: "Mecánica: Ruedas en genuflexión tirando cuerda tras nuca. Curva el vientre superior encogiendo psoas hacia adentro expulsando aire destruyendo placas de rectos para marcar bloque central de peso profundo masivo volúmen fuerte duro masivo pared titan asilada baja hipertrofia pura." },
  { name: "Ab wheel rollout", muscle_group: "Abdominales", category: "isolation", joint_type: "Multiarticular", muscles: "Aislamiento core excéntrico pared lateral anterior densa y estática transverso.", description: "Mecánica: Cadena en plancha guiada rodando y destruyendo pared transversal abdominal soportando todo eje esquelético elongándose de forma infernal bajo gravedad sin arco lumboso peligroso duro fuerte masivo denso constructor estático." },
  { name: "Muscle up en anillas", muscle_group: "Cuerpo completo", category: "calisthenics", joint_type: "Multiarticular", muscles: "Pectoral, Lats, Tríceps estabilizadores nerviosos estables.", description: "Mecánica: Atraviesa la barrera tracción empuje con control gimnástico rotando anillas falsas y demandando coordinación neurológica sinérgica impecable brutalidad libre peso estética suprema fuerza técnica densa pura." },
];
